apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: seafile
---
apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Parsers_File parsers.conf
        HTTP_Server  Off
        Log_File     /dev/stderr

    [INPUT]
        Name     tail
        Tag      ccnet
        Path     /opt/haiwen/logs/ccnet.log
        DB       /opt/haiwen/logs/.fluentbit.ccnet.db
        Parser   seafile

    [INPUT]
        Name     tail
        Tag      seafile
        Path     /opt/haiwen/logs/seafile.log
        DB       /opt/haiwen/logs/.fluentbit.seafile.db
        Parser   seafile

    [INPUT]
        Name     tail
        Tag      controller
        Path     /opt/haiwen/logs/controller.log
        DB       /opt/haiwen/logs/.fluentbit.controller.db
        Parser   seafile

    [INPUT]
        Name                tail
        Tag                 seahub
        Path                /opt/haiwen/logs/seahub.log
        DB                  /opt/haiwen/logs/.fluentbit.seahub.db
        Multiline           On
        Parser_Firstline    seahub
        Buffer_Max_Size     64k

    [OUTPUT]
        Name                stdout
        Match               *
        Format              json_lines
        json_date_format    iso8601
  parsers.conf: |
    [PARSER]
        Name        seafile
        Format      regex
        Regex       ^\[(?<time>[0-9]{2}/[0-9]{2}/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})\] ((?<source_line>[^ ]+): )?(?<log>.+)$
        Time_Key    time
        Time_Format %D %T

    [PARSER]
        Name        seafile2
        Format      regex
        Regex       ^\[(?<time>[0-9]{2}/[0-9]{2}/[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2} (AM|PM))\] ((?<source_line>[^ ]+): )?(?<log>.+)$
        Time_Key    time
        Time_Format %m/%d/%Y %r

    [PARSER]
        Name        seahub
        Format      regex
        Regex       ^(?<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}) \[(?<level>[A-Z]+)\] (?<source_line>[^ ]+) (?<source_func>[^ ]+) (?<log>.+)$
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S,%L
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: fluent-bit-g624bm678m
  namespace: seafile
---
apiVersion: v1
data:
  nginx.conf: "worker_processes auto;\nerror_log stderr;\n\nevents { \n}\n\nhttp {\n
    \   proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=cache:30m max_size=30m;\n
    \   proxy_temp_path /tmp/nginx_proxy 1 2;\n\n    log_format json_combined escape=json\n
    \   '{'\n        '\"time_local\":\"$time_local\",'\n        '\"remote_addr\":\"$remote_addr\",'\n
    \       '\"remote_user\":\"$remote_user\",'\n        '\"request\":\"$request\",'\n
    \       '\"status\": \"$status\",'\n        '\"body_bytes_sent\":\"$body_bytes_sent\",'\n
    \       '\"request_time\":\"$request_time\",'\n        '\"http_referrer\":\"$http_referer\",'\n
    \       '\"http_user_agent\":\"$http_user_agent\"'\n    '}';\n    access_log /dev/stdout
    json_combined;\n\n    server_tokens off;\n\n    server {\n        listen      8080
    default_server;\n        server_name _;\n\n        real_ip_header X-Forwarded-For;\n
    \       set_real_ip_from 10.0.0.0/8;\n        set_real_ip_from 192.168.0.0/16;\n
    \       set_real_ip_from 172.16.0.0/12;\n        set_real_ip_from fd00::/8;\n\n
    \       location / {\n            proxy_pass         http://127.0.0.1:8000;\n
    \           proxy_set_header   Host $host;\n            proxy_read_timeout  1200s;\n\n
    \           # used for view/edit office file via Office Online Server\n            client_max_body_size
    0;\n        }\n\n        location /seafhttp {\n            rewrite ^/seafhttp(.*)$
    $1 break;\n            proxy_pass http://127.0.0.1:8082;\n            client_max_body_size
    0;\n\n            proxy_connect_timeout  36000s;\n            proxy_read_timeout
    \ 36000s;\n            proxy_send_timeout  36000s;\n\n            send_timeout
    \ 36000s;\n        }\n\n        location /media {\n            proxy_pass         http://127.0.0.1:8000;\n
    \           proxy_set_header   Host $host;\n\n            proxy_cache cache;\n
    \           proxy_cache_valid 4h;\n            proxy_cache_key $request_uri;\n
    \       }\n    }\n}\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: nginx-gf24ggm882
  namespace: seafile
---
apiVersion: v1
data:
  MYSQL_OPTIONAL_PARAMS: LWUgMSAtcyBzZWFmaWxlIC1jIHNlYWZpbGUgLWIgc2VhZmlsZQ==
  MYSQL_SERVER: bWFyaWFkYg==
  MYSQL_USER: c2VhZmlsZQ==
  MYSQL_USER_PASSWORD: c2VhZmlsZQ==
  SEAFILE_ADMIN: ZXhhbXBsZUBleGFtcGxlLmNvbQ==
  SEAFILE_ADMIN_PW: dGVzdA==
  SEAFILE_NAME: c2VhZmlsZQ==
  SEAFILE_PUBLIC_URL: aHR0cDovL2xvY2FsaG9zdA==
kind: Secret
metadata:
  name: seafile-env-84mkm84728
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: seafile
  namespace: seafile
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: seahub
    port: 8000
    protocol: TCP
    targetPort: seahub
  - name: seafile
    port: 8082
    protocol: TCP
    targetPort: seafile
  selector:
    app.kubernetes.io/name: seafile
    seafile: seafile
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: seafile
  namespace: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seafile
      seafile: seafile
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seafile
        seafile: seafile
    spec:
      containers:
      - args:
        - run_only
        envFrom:
        - secretRef:
            name: seafile-env
        image: bslawianowski/seafile:7.1.4
        livenessProbe:
          httpGet:
            path: /api2/ping
            port: seahub
          initialDelaySeconds: 60
          periodSeconds: 20
        name: seafile
        ports:
        - containerPort: 8082
          name: seafile
        - containerPort: 8000
          name: seahub
        readinessProbe:
          httpGet:
            path: /api2/ping
            port: seahub
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - mountPath: /opt/haiwen/logs
          name: logs
        - mountPath: /seafile
          name: data
      - args:
        - /fluent-bit/bin/fluent-bit
        - -c
        - /config/fluent-bit.conf
        image: fluent/fluent-bit:1.4
        name: fluentbit
        volumeMounts:
        - mountPath: /config
          name: fluent-bit-config
          readOnly: true
        - mountPath: /opt/haiwen/logs
          name: logs
      - image: nginx:1.19
        name: nginx
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          readOnly: true
          subPath: nginx.conf
      enableServiceLinks: false
      initContainers:
      - args:
        - init_only
        envFrom:
        - secretRef:
            name: seafile-env
        image: bslawianowski/seafile:7.1.4
        name: seafile-init
        volumeMounts:
        - mountPath: /opt/haiwen/logs
          name: logs
        - mountPath: /seafile
          name: data
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          name: fluent-bit-g624bm678m
        name: fluent-bit-config
      - configMap:
          name: nginx-gf24ggm882
        name: nginx-config
      - emptyDir: {}
        name: logs
      - name: data
        persistentVolumeClaim:
          claimName: seafile-data
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: seafile
  namespace: seafile
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: seafile
          servicePort: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: seafile-data
  namespace: seafile
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
