apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: fluent-bit
  files:
  - fluent-bit/fluent-bit.conf
  - fluent-bit/parsers.conf
- name: nginx
  files:
  - nginx/nginx.conf
secretGenerator:
- name: seafile-env
  env: env.txt
  type: Opaque
commonLabels:
  app.kubernetes.io/name: seafile
namespace: seafile
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
